### ISSUE TITLE
Helm installation failed: No matches for kind "Certificate" in version "cert-manager.io/v1"

### ISSUE THREAD

**Issue by b3n3w** [timescale/tobs#354]
**What happened?**

Helm is unable to create the containers due to an error.

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"]

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

Running the following command:
helm install --version 0.10.0-alpha test timescale/tobs

**Environment**

* tobs installation method:

- [ ] cli
- [x] helm chart

* tobs version:

    `0.10.0-alpha`
    
    

* Kubernetes version information:

    `latest kind cluster`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* tobs Logs:

```
insert tobs logs relevant to the issue here
```

**Anything else we need to know?**:

Trying to install the test environment into a kind cluster.

**Comment by paulfantom** [comment]
This error is a result of the lack of cert-manager installed. Due to opentelemetry-operator hard requirement of cert-manager, tobs helm chart also inherits that requirement. As such starting from tobs 0.10.0 we will require users to have cert-manager preinstalled (as described in https://github.com/timescale/tobs/tree/master/chart#prerequisites) or to disable installation of opentelemetry-operator (flag `opentelemetryOperator.enabled=false`). We are working on removing this hard dependency as part of https://github.com/timescale/tobs/issues/198.

Sorry for your inconvenience.

I am closing this issue as a won't fix. Further tracking of this is done in https://github.com/timescale/tobs/issues/198.
