### ISSUE TITLE
[splike] enable SPM-like feature in tobs

### ISSUE THREAD

**Issue by paulfantom** [timescale/tobs#454]
Jaeger added [SPM experimental feature](https://www.jaegertracing.io/docs/1.35/spm/). It would be good to reconsider if tobs should ship Jaeger UI with pre-configured SPM or if there are other possibilities (like similar thing in grafana UI).

**Comment by ramonguiu** [comment]
Given the current stability of the SPM feature (it's experimental and the otel collector span metrics processor it's still not very stable) I would remove from the current epic for now and we can reconsider again for a future one.

**Comment by VineethReddy02** [comment]
Any reason why we are scoping this task into `promscale-on-cloud` epic? I see it as more related to `Tobs production readiness` epic.

**Comment by paulfantom** [comment]
> Any reason why we are scoping this task into promscale-on-cloud epic? I see it as more related to Tobs production readiness epic.

It should be part of both. From one side this is obviously a part of production readiness effort but at the same time it requires us to refactor tracing part of the stack which affects our efforts in `promscale-on-cloud` effort

**Comment by ramonguiu** [comment]
I would leave this one out for now. Production readiness will be an ongoing effort. We don't need to have one huge epic that has everything we can think of will be part of this. Let's work step by step, addressing the most important issues first and create other epics to improve it later.
In this particular case, we don't need this feature shipped with tobs yet, even more since it's experimental on the Jaeger side (i.e. , not production ready).
