### ISSUE TITLE
Flux V2 Support

### ISSUE THREAD

**Issue by deeco** [timescale/tobs#587]
Tried to install Timescale via Helm Controller in Flux

**Did you expect to see some different?**

**Environment**

k8s and flux v2

* Which helm chart and what version are you using?

latest

* What is in your `values.yaml` ?

default

* Kubernetes version information:

  `kubectl version`
 1.23.4
    
    
    
  `---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: timescale/tobs
  namespace: tobs
spec:
  interval: 1m
  url: https://charts.timescale.com/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: timescale/tobs
  namespace: tobs
spec:
  interval: 1m
  url: https://github.com/timescale/helm-charts
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/`  
  

* Kubernetes cluster kind:

  insert how you created your cluster: kops, bootkube, etc.

**Anything else we need to know?**:

**Comment by deeco** [comment]
Trying to add via flux is manifest and deploy, are the above repos the correct source ?

**Comment by nhudson** [comment]
I am not really sure what the issue is to be able to even help you.  

What version of the chart are you using?  
What is the actual issue?  
Logs? 
Errors?

If you're just asking if the `HelmRelease` object you posted above is correct, the `url` is correct.  You don't need to define the chart name or a namespace either.  At least not with any Flux workflow I have seen.  It should be something like this

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: timescale
spec:
  interval: 5m
  url: https://charts.timescale.com/
```

Then next you will need to define your `values.yaml` and a `HelmRelease` object to install it via the helm chart.
